config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/Yousaf95/JAVA:
      branch: main
      repo: https://github.com/Yousaf95/JAVA.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/Yousaf95/JAVA git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-mauve-jackal.sh
        container: qc.acc_chummy-flax-hummingbird
  QC.Doc:
    repos:
      github.com/Yousaf95/JAVA find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-dandelion-bordeaux.sh
        container: qc.doc_whiny-red-beaver
      github.com/Yousaf95/JAVA git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-emerald-impala.sh
        container: qc.doc_breezy-asparagus-millipede
  QC.Lic:
    repos:
      github.com/Yousaf95/JAVA licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-denim-angelfish.sh
        container: qc.lic_tasty-burgundy-rhinoceros
  QC.Sty:
    repos:
      github.com/Yousaf95/JAVA checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-pear-gibbon.sh
        container: qc.sty_flabby-indigo-opossum
  QC.Ver:
    repos:
      github.com/Yousaf95/JAVA get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-ivory-fousek.sh
        container: qc.ver_slaphappy-grey-saola
timeout: 5400
