config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/Yousaf95/JAVA:
      branch: main
      repo: https://github.com/Yousaf95/JAVA.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/Yousaf95/JAVA git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-black-akita.sh
        container: qc.acc_shabby-lime-heron
  QC.Doc:
    repos:
      github.com/Yousaf95/JAVA find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-scarlet-shrimp.sh
        container: qc.doc_hazy-auburn-beaver
      github.com/Yousaf95/JAVA git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-razzmatazz-sparrow.sh
        container: qc.doc_wheezy-olive-kingfisher
  QC.Lic:
    repos:
      github.com/Yousaf95/JAVA licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-ochre-chin.sh
        container: qc.lic_wheezy-ecru-mau
  QC.Sty:
    repos:
      github.com/Yousaf95/JAVA checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-wheat-koala.sh
        container: qc.sty_pokey-flax-ocelot
  QC.Ver:
    repos:
      github.com/Yousaf95/JAVA get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-xanthic-dragon.sh
        container: qc.ver_fuzzy-purple-moose
timeout: 5400
